# Generated by Django 5.0 on 2024-01-04 16:07

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='menuitem',
            name='image',
            field=models.ImageField(default=django.utils.timezone.now, upload_to='menu_images/'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='menuitem',
            name='menu_item_description',
            field=models.CharField(default='', max_length=1000),
        ),
    ]
